# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Fast, scriptable CLI for the Google Play Developer API"
  homepage "https://github.com/aljrico/Google-Play-Console-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aljrico/Google-Play-Console-CLI/releases/download/v0.1.0/gpc_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "1f92a98963cdc28c0438eff1a7357db6d9da37e8d070dbe5b9b86c50048089a8"

      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aljrico/Google-Play-Console-CLI/releases/download/v0.1.0/gpc_0.1.0_Darwin_arm64.tar.gz"
      sha256 "15046a0556d6768515f357b5bf943dd9adf66b144967d773074166d661645489"

      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aljrico/Google-Play-Console-CLI/releases/download/v0.1.0/gpc_0.1.0_Linux_x86_64.tar.gz"
      sha256 "e70ae01893ed59949e28b8d7f8839d5e2a9226eb003f2042d2620f5e0e791813"
      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aljrico/Google-Play-Console-CLI/releases/download/v0.1.0/gpc_0.1.0_Linux_arm64.tar.gz"
      sha256 "1ae4724861fa14e0fee632246863e85ceab32479065d62cf2451d0bfa4984cd4"
      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  test do
    system "#{bin}/gpc", "version"
  end
end
